export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

export const SEARCH_PROFILE_REQUEST = 'SEARCH_PROFILE_REQUEST';
export const SEARCH_PROFILE_SUCCESS = 'SEARCH_PROFILE_SUCCESS';
export const SEARCH_PROFILE_ERROR = 'SEARCH_PROFILE_ERROR';

export const CREATE_VITALS_REQUEST = 'CREATE_VITALS_REQUEST';
export const CREATE_VITALS_SUCCESS = 'CREATE_VITALS_SUCCESS';
export const CREATE_VITALS_ERROR = 'CREATE_CASE_ERROR';

export const CREATE_CASE_REQUEST = 'CREATE_CASE_REQUEST';
export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS';
export const CREATE_CASE_ERROR = 'CREATE_CASE_ERROR';

export const FETCH_CASE_REQUEST = 'FETCH_CASE_REQUEST';
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS';
export const FETCH_CASE_ERROR = 'FETCH_CASE_ERROR';

export const CREATE_CASE_FOLDER_REQUEST = 'CREATE_CASE_FOLDER_REQUEST';
export const CREATE_CASE_FOLDER_SUCCESS = 'CREATE_CASE_FOLDER_SUCCESS';
export const CREATE_CASE_FOLDER_ERROR = 'CREATE_CASE_FOLDER_ERROR';

export const FETCH_MEDICINE_REQUEST = 'FETCH_MEDICINE_REQUEST';
export const FETCH_MEDICINE_SUCCESS = 'FETCH_MEDICINE_SUCCESS';
export const FETCH_MEDICINE_ERROR = 'FETCH_MEDICINE_ERROR';