export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

export const CREATE_PATIENT_REQUEST = 'CREATE_PATIENT_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_ERROR = 'CREATE_PATIENT_ERROR';
export const CREATE_PATIENT_RESET = 'CREATE_PATIENT_RESET';

export const SEARCH_PATIENT_REQUEST = 'SEARCH_PATIENT_REQUEST';
export const SEARCH_PATIENT_SUCCESS = 'SEARCH_PATIENT_SUCCESS';
export const SEARCH_PATIENT_ERROR = 'SEARCH_PATIENT_ERROR';

export const FETCH_PATIENT_LIST_REQUEST = 'FETCH_PATIENT_LIST_REQUEST';
export const FETCH_PATIENT_LIST_SUCCESS = 'FETCH_PATIENT_LIST_SUCCESS';
export const FETCH_PATIENT_LIST_ERROR = 'FETCH_PATIENT_LIST_ERROR';

export const QUEUE_PATIENT_REQUEST = 'QUEUE_PATIENT_REQUEST'
export const QUEUE_PATIENT_SUCCESS = 'QUEUE_PATIENT_SUCCESS'
export const QUEUE_PATIENT_ERROR = 'QUEUE_PATIENT_ERROR'

export const ATTACH_METADATA_REQUEST = 'ATTACH_METADATA_REQUEST';
export const ATTACH_METADATA_SUCCESS = 'ATTACH_METADATA_SUCCESS';
export const ATTACH_METADATA_ERROR = 'ATTACH_METADATA_ERROR';

export const TRANSFER_PATIENT_REQUEST = 'TRANSFER_PATIENT_REQUEST';
export const TRANSFER_PATIENT_SUCCESS = 'TRANSFER_PATIENT_SUCCESS';
export const TRANSFER_PATIENT_ERROR = 'TRANSFER_PATIENT_ERROR';

export const RESET_PATIENT_QUEUE = 'RESET_PATIENT_QUEUE';

export const FETCH_PATIENT_QUEUE_REQUEST = 'FETCH_PATIENT_QUEUE_REQUEST';
export const FETCH_PATIENT_QUEUE_SUCCESS = 'FETCH_PATIENT_QUEUE_SUCCESS';
export const FETCH_PATIENT_QUEUE_ERROR = 'FETCH_PATIENT_QUEUE_ERROR';

export const ADD_VITALS_REQUEST = 'ADD_VITALS_REQUEST';
export const ADD_VITALS_SUCCESS = 'ADD_VITALS_SUCCESS';
export const ADD_VITALS_ERROR = 'ADD_VITALS_ERROR';

export const ADD_CHIEF_COMPLAINTS_REQUEST = 'ADD_CHIEF_COMPLAINTS_REQUEST';
export const ADD_CHIEF_COMPLAINTS_SUCCESS = 'ADD_CHIEF_COMPLAINTS_ERROR';
export const ADD_CHIEF_COMPLAINTS_ERROR = 'ADD_CHIEF_COMPLAINTS_ERROR';

export const CREATE_CASE_REQUEST = 'CREATE_CASE_REQUEST';
export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS';
export const CREATE_CASE_ERROR = 'CREATE_CASE_ERROR';

export const UPDATE_MEDICAL_HISTORY_REQUEST = 'UPDATE_MEDICAL_HISTORY_REQUEST';
export const UPDATE_MEDICAL_HISTORY_SUCCESS = 'UPDATE_MEDICAL_HISTORY_SUCCESS';
export const UPDATE_MEDICAL_HISTORY_ERROR = 'UPDATE_MEDICAL_HISTORY_ERROR';

export const FETCH_CASE_REQUEST = 'FETCH_CASE_REQUEST';
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS';
export const FETCH_CASE_ERROR = 'FETCH_CASE_ERROR';

export const CREATE_CASE_FOLDER_REQUEST = 'CREATE_CASE_FOLDER_REQUEST';
export const CREATE_CASE_FOLDER_SUCCESS = 'CREATE_CASE_FOLDER_SUCCESS';
export const CREATE_CASE_FOLDER_ERROR = 'CREATE_CASE_FOLDER_ERROR';

export const FETCH_MEDICINE_REQUEST = 'FETCH_MEDICINE_REQUEST';
export const FETCH_MEDICINE_SUCCESS = 'FETCH_MEDICINE_SUCCESS';
export const FETCH_MEDICINE_ERROR = 'FETCH_MEDICINE_ERROR';

export const FETCH_MEDICAL_DIAGNOSIS_REQUEST = 'FETCH_MEDICAL_DIAGNOSIS_REQUEST';
export const FETCH_MEDICAL_DIAGNOSIS_SUCCESS = 'FETCH_MEDICAL_DIAGNOSIS_SUCCESS';
export const FETCH_MEDICAL_DIAGNOSIS_ERROR = 'FETCH_MEDICAL_DIAGNOSIS_ERROR';

export const ADD_MEDICAL_DIAGNOSIS_REQUEST = 'ADD_MEDICAL_DIAGNOSIS_REQUEST';
export const ADD_MEDICAL_DIAGNOSIS_SUCCESS = 'ADD_MEDICAL_DIAGNOSIS_SUCCESS';
export const ADD_MEDICAL_DIAGNOSIS_ERROR = 'ADD_MEDICAL_DIAGNOSIS_ERROR';

export const ADD_GYNAECOLOGY_INFO_REQUEST = 'ADD_GYNAECOLOGY_INFO_REQUEST';
export const ADD_GYNAECOLOGY_INFO_SUCCESS = 'ADD_GYNAECOLOGY_INFO_SUCCESS';
export const ADD_GYNAECOLOGY_INFO_ERROR = 'ADD_GYNAECOLOGY_INFO_ERROR';

export const UPDATE_SCREENING_RESULT_REQUEST = 'UPDATE_SCREENING_RESULT_REQUEST';
export const UPDATE_SCREENING_RESULT_SUCCESS = 'UPDATE_SCREENING_RESULT_SUCCESS';
export const UPDATE_SCREENING_RESULT_ERROR = 'UPDATE_SCREENING_RESULT_ERROR';

export const UPDATE_MEDICAL_CONDITION_REQUEST = 'UPDATE_MEDICAL_CONDITION_REQUEST';
export const UPDATE_MEDICAL_CONDITION_SUCCESS = 'UPDATE_MEDICAL_CONDITION_SUCCESS';
export const UPDATE_MEDICAL_CONDITION_ERROR = 'UPDATE_MEDICAL_CONDITION_ERROR';

export const FETCH_MEDICAL_RECORDS_REQUEST = 'FETCH_MEDICAL_RECORDS_REQUEST';
export const FETCH_MEDICAL_RECORDS_SUCCESS = 'FETCH_MEDICAL_RECORDS_SUCCESS';
export const FETCH_MEDICAL_RECORDS_ERROR = 'FETCH_MEDICAL_RECORDS_ERROR';

export const CHECK_TRIAGE_ITEM = 'CHECK_TRIAGE_ITEM'

export const DISMISS_ERROR = 'DISMISS_ERROR';